config/routes.rb
Rails.application.routes.draw do
  get 'dash/admin'
  get 'dash/customer'
  get 'dash/policy_handle'
  get 'dash/user_handle'
  get 'dash/poltype_handle'
  get 'dash/company_handle'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'details/make_admin'
  get 'details/cedit'
  get 'details/cdestroy'
  get 'details/cshow'
  get 'details/cupdate'
  get 'details/display'
  get 'policies/display'
  get 'companies/companyShow'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :details
  resources :poltypes
  resources :companies
  resources :policies
  resources :posts
  resources :comments
  root to: "sessions#new"

end

app/models/company.rb
class Company < ApplicationRecord
	has_many :poltype,:dependent => :destroy
	has_many :policy, :dependent => :destroy 
	validates :name, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    if user_signed_in?
		  @companies= Company.all
    else
      redirect_to new_user_session_path
    end
	end

  def companyShow
    if user_signed_in?
      @company = Company.find_by_id(params[:id])
    else
      redirect_to new_user_session_path
    end
 
  end

	def show
	end
	def new
    if user_signed_in?
		  @company = Company.new
      @user = current_user
      @u_detail = @user.detail
    else
      redirect_to new_user_session_path
    end
	end
	def create
		 @company= Company.new(company_params)
		 if @company.save
  		redirect_to dash_admin_path
  	else
  			render 'new'
  	end
	end
  def edit
    if user_signed_in?
      @company = Company.find(params[:id])
      @user = current_user
      @u_detail = @user.detail
    else
      redirect_to new_user_session_path
    end
    
  end

	def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to dash_admin_path, :notice => "company edited!!" 
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @pol_d = Policy.where(:company_id => @company.id)
    @pol_d.each do |i|
      i.destroy
      
    end
    @company.destroy
 
    redirect_to companies_path, :notice => "company deleted"
  end


 private

  def company_params
  	params.require(:company).permit(:name, :description)
  end
end

app/views/companies/_form.html.erb
<div class="container box-form">
  <%= simple_form_for @company do |f| %>
    <%= f.input :name, placeholder: "name of company" %>
    <%= f.input :description, placeholder: "description of company" %>
    <%= f.submit "submit" , :class => "btn btn-primary custom_btn_small"%>
  <% end %>
</div>

app/views/companies/_head.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Insurence Manager</a>
    </div>
    <% if user_signed_in? %>
     <% @user= current_user %>
    <% @user_details = @user.detail %>
    <ul class="nav navbar-nav navbar-right" style="text-align: center;">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <%= @user_details.first_name %>
        <span class="caret"></span></a>
        <ul class="dropdown-menu" style="text-align: center;>
          <li><a href="#">edit</a></li>
          <li> <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %></li>
        </ul>
        <% end %>
      </li>
    </ul>
  </div>

</nav>

app/views/companies/companyShow.html.erb
<div class="container">
  <%= link_to "back", companies_path,:class => "btn btn-primary custom_btn_small" %>
</div>
<% @plan=Poltype.where(:company_id => @company.id) %>
<% if @plan.count!=0 %>
  <div class="container">
    <h1 class="form-info">all the plans of the company: <%= @company.name %> </h1>
    <% @plan.each do |i| %>
      <div class="container show-box">
        <h2><%=i.name%></h2>
        <p><strong>description:</strong> <%=i.description%> </p><br>
        <p><strong>duration:</strong> <%=i.duration%> years <br></p>
        <p><strong>Insured Amount:</strong> <%=i.sum_insured%> INR <br></p>
        <p><strong>Premium Amount:</strong> <%=i.premium_amount%> INR<br></p>
        <td> <%= link_to "buy", new_policy_path(:company_id => i.company_id,:poltype_id => i.id),:class => "btn btn-primary custom_btn_small" %><td>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="container">
    <h1 class="form-info">there are no plans of the company: <%= @company.name %> </h1>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1 class="form-info">edit company</h1>
<% @user = current_user %>
<% @u_detail = @user.detail %>
<%= render "form" %>

app/views/companies/index.html.erb
<% @user = current_user %>
<% @u_detail = @user.detail %>
<% if(@companies.count!=0) %>
  <div class="container" >
    <h2 class="form-info">Companies</h2>
    <p class="text-style">this list displays all the available companies. this list is only for viewing, to select a company and buy a policy from a specific company , please visit <strong>Policy --> Add new policy</strong> </p><br><br>            
    <table class="table table-hover table-responsive">
      <thead class="thead-inverse">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
        <% @companies.each do |i| %>
        <tr>
          <td><%=i.name%></td>
          <td><%=i.description %></td>
          <td><%= link_to "plans", companies_companyShow_path(:id => i.id), :class => "btn btn-primary custom_btn_small" %></td>
          <% if @u_detail.admin == true %>
            <td><%= link_to "edit", edit_company_path(i), :class => "btn btn-primary custom_btn_small" %></td>
            <td><%= link_to 'Destroy', company_path(i),
                method: :delete,
                data: { confirm: 'Are you sure?' } , :class => "btn btn-primary custom_btn_small"%></td>
           <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
   <div class="container" >
    <h2 class="form-info">no companies available</h2>
    <p class="text-style">please come back later</p><br><br>            
  </div>
<% end %>

app/views/companies/new.html.erb
<h1 class="form-info"> new company </h1>
<% @user = current_user %>
<% @u_detail = @user.detail %>
<%= render "form" %>