config/routes.rb
Rails.application.routes.draw do
  get 'dash/admin'
  get 'dash/customer'
  get 'dash/policy_handle'
  get 'dash/user_handle'
  get 'dash/poltype_handle'
  get 'dash/company_handle'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'details/make_admin'
  get 'details/cedit'
  get 'details/cdestroy'
  get 'details/cshow'
  get 'details/cupdate'
  get 'details/display'
  get 'policies/display'
  get 'companies/companyShow'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :details
  resources :poltypes
  resources :companies
  resources :policies
  resources :posts
  resources :comments
  root to: "sessions#new"

end

app/models/detail.rb
class Detail < ApplicationRecord
	belongs_to :user
	self.primary_key = "email"
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :contact_number,presence: true, :numericality => {:only_integer => true}, length: { is: 10 , message: "length should be 10"} 
	validates :address, format: { with: /\A[a-zA-Z0-9, .]*\z/,
    message: "only letters numbers \",\" \".\" and space are allowed" }, presence: true
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    @det = Detail.find_by_user_id(current_user.id)
    if (user_signed_in? && @det.admin==true)
      @details = Detail.all
    else
      redirect_to dash_admin_path
    end
  end
  def show
  
  end

  def new
	  if user_signed_in?
		  @user=current_user
  	  @detail = Detail.new
    else
      redirect_to new_user_session_path
    end
  end
  def cedit
    if user_signed_in?
      @detail= Detail.find_by_user_id(params[:user_id])
      @user = current_user
      @u_detail = @user.detail
    else
      redirect_to new_user_session_path

    end
  end

  def display
     @det = Detail.find_by_user_id(current_user.id)
    if (user_signed_in? && @det.admin==true)
      @detail= Detail.find_by_user_id(params[:user_id])
      @user = current_user
      @u_detail= @user.detail
    else
      redirect_to dash_admin_path
    end
  end
  
  def update
    @detail= Detail.find_by_user_id(params[:user_id])
    @detail.email = @detail.email
    @detail.user_id = @detail.user_id
    if @detail.update(detail_params)
      redirect_to details_path, :notice => "user details edited!!" 
    else
      @detail.update(detail_params)
      render 'cedit'
    end  
  end
  def cupdate
    @detail= Detail.find_by_user_id(params[:user_id])
    @detail.email = @detail.email
    @detail.user_id = @detail.user_id
    if @detail.update(detail_params)
     redirect_to dash_admin_path, :notice => "user details edited!!" 
    else
      @det.update(detail_params)
      render 'cedit'
    end
  end
  def destroy
    @detail= Detail.find_by_user_id(params[:user_id])
    @usr_del = User.find(@detail.user_id)
    @detail.destroy
    @usr_del.destroy
 
    redirect_to details_path, :notice => "user deleted"
  end
  def make_admin
    @detail= Detail.find_by_user_id(params[:user_id])
    @detail.toggle :admin
    @detail.save
    if @detail.save
      flash[:notice] = "the user was made admin"
      redirect_to details_path
    else
      flash[:notice] = "the user was not made admin"
      redirect_to details_path
    end
  end 

  def create
    @detail = Detail.new(detail_params)
  	@detail.email = current_user.email
  	@detail.user_id = current_user.id 
    @detail.save
    if @detail.save
  		redirect_to dash_customer_path
    else
      @detail = Detail.new(detail_params)
      @detail.email = current_user.email
      @detail.user_id = current_user.id 
      @detail.save
      render 'new'
  	end
  end

private
  def detail_params
  	params.require(:detail).permit(:first_name, :last_name, :admin, :contact_number, :address)
  end

end

app/views/details/_form.html.erb
<div class="container box-form">
  <% if user_signed_in? %>
    <% @user=current_user %>
    <%	@whoadmins = Detail.where(:admin => true )%>

    <% @ary= Array.new %>
    <% @whoadmins.each do |i| %>
      <% @ary.push(i.email) %>
    <% end %>

    <%= simple_form_for @detail do |f| %>
      <% if @detail.errors.any? %>
        <div id="error_explanation" style="color: red;">
          <h2>
          <%= pluralize(@detail.errors.count, "error") %> prohibited
          this detail from being saved:
          </h2>
          <ul>
          <% @detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :first_name, placeholder: 'First Name' %>
      <%= f.input :last_name, placeholder: 'Last Name' %>
      <%= f.input :admin, input_html: {value: 0}, :readonly => true,:as => :hidden %>
      <%= f.input :contact_number, placeholder: 'Contact Number'%>
      <%= f.input :address, placeholder: 'Address' %>
      <%= f.button :submit, :class => "btn btn-primary custom_btn_small" %>
    <% end %>
  <% else %>
    <p>user not signed in</p>
  <% end %>
</div>

app/views/details/cedit.html.erb
<div class="container box-form">
  <% if user_signed_in? %>
    <% @user = current_user %>
    <%  @u_detail = @user.detail %>
    <%= simple_form_for @detail, :url => details_cupdate_path(:user_id => @detail.user_id) do |f| %>
      <% if @detail.errors.any? %>
        <div id="error_explanation" style="color: red;">
          <h2>
          <%= pluralize(@detail.errors.count, "error") %> prohibited
          this detail from being saved:
          </h2>
          <ul>
          <% @detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :email, input_html: {value: @detail.email}, :readonly => true,  :label => "email (not allowed to update)"%>
      <%= f.input :user_id, input_html: {value: @detail.user_id}, :as => :hidden%>
      <%= f.input :first_name, input_html: {value: @detail.first_name}, :label => "First Name"%>
      <%= f.input :last_name, input_html: {value: @detail.last_name}, :label => "Last Name"%>
      <% if @detail.admin == true %>
        <%= f.input :admin, input_html: {value: 1}, :readonly => true,:as => :hidden %>
      <% else %>
        <%= f.input :admin, input_html: {value: 0}, :readonly => true,:as => :hidden %>
      <% end %>
      <%= f.input :contact_number, input_html: {value: @detail.contact_number}, :label => "Contact Number"%>
      <%= f.input :address, input_html: {value: @detail.address}, :label => "Address"%>
      <%= f.button :submit, 'update', :class => "btn btn-primary custom_btn_small" %>
    <% end %>
  <% else %>
    <p>user not signed in</p>
  <% end %>
</div>

app/views/details/display.html.erb
<div class="container show-box">
  <p><strong>Name :</strong><%= @detail.first_name%> <%=@detail.last_name%></p><br>

  <p><strong>address :</strong><%= @detail.address%></p><br>
  <p><strong>email :</strong><%= @detail.email%></p><br>
  <p><strong>user type :</strong>
  <% if@detail.admin==true %>
    <%= "admin" %>
  <% else%>
    <%= "customer" %>
  <% end %>
  </p><br>
  <p><strong>contact number :</strong><%= @detail.contact_number %></p><br>
  <% if @u_detail.admin == true %>
    <%= link_to "edit", details_cedit_path(:user_id => @detail.user_id),:class => "btn btn-primary custom_btn_small" %><br>
    <%= link_to 'Destroy', details_cdestroy_path(:user_id => @detail.user_id),
    method: :delete,
    data: { confirm: 'Are you sure?' } , :class => "btn btn-primary custom_btn_small"%><br>
    <% if @detail.admin == false %>
      <%= link_to "make admin", details_make_admin_path(:user_id => @detail.user_id),:class => "btn btn-primary custom_btn_small" %><br>
      <%= link_to "back", details_path,:class => "btn btn-primary custom_btn_small" %>

    <%end%>
  <%end%>


</div>

app/views/details/index.html.erb
<% @user = current_user %>
<% @u_detail = @user.detail %>
<div class="container"  >
  <h2 class="form-info">all users</h2>
  <p class="text-style">this list displays all the users</p><br><br>                   
  <table class="table table-hover table-responsive">
    <thead class="thead-inverse">
      <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th></th>
      </tr>
    </thead>
    <tbody>
      <% @details.each do |i| %>
        <tr>
        <td><%=i.first_name%></td>
        <td><%=i.last_name%></td>
        <td><%= link_to "display", details_display_path(:user_id => i.user_id),:class => "btn btn-primary custom_btn_small" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/details/new.html.erb
<div class="container form-box">
  <h1> please enter your details </h1>
  <% if user_signed_in? %>
    <% @user=current_user %>
    <%= simple_form_for @detail do |f| %>
      <% if @detail.errors.any? %>
        <div id="error_explanation" style="color: red;">
          <h2>
          <%= pluralize(@detail.errors.count, "error") %> prohibited
          this detail from being saved:
          </h2>
          <ul>
          <% @detail.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.input :first_name, placeholder: 'First Name' %>
      <%= f.input :last_name, placeholder: 'Last Name' %>
      <%= f.input :admin, input_html: {value: 0}, :readonly => true,:as => :hidden %>
      <%= f.input :contact_number, placeholder: 'Contact Number'%>
      <%= f.input :address, placeholder: 'Address' %>
      <%= f.button :submit , :class => "btn btn-primary custom_btn_small"%>
    <% end %>
  <% else %>
    <p>user not signed in</p>
  <% end %>
</div>