config/routes.rb
Rails.application.routes.draw do
  get 'dash/admin'
  get 'dash/customer'
  get 'dash/policy_handle'
  get 'dash/user_handle'
  get 'dash/poltype_handle'
  get 'dash/company_handle'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'details/make_admin'
  get 'details/cedit'
  get 'details/cdestroy'
  get 'details/cshow'
  get 'details/cupdate'
  get 'details/display'
  get 'policies/display'
  get 'companies/companyShow'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :details
  resources :poltypes
  resources :companies
  resources :policies
  resources :posts
  resources :comments
  root to: "sessions#new"

end

app/views/layouts/_action_nav.html.erb
<% @c = controller.controller_name %>
<% @a = controller.action_name %>
<% @ac = @c + @a %>
<% if user_signed_in? && @ac != "detailsnew" && @ac != "detailscreate"%>
  <% @ud = Detail.find_by_user_id(current_user.id) %>
  <div class="container action_stub" >
    <ul class="list-inline" >
      <% if controller.action_name == "company_handle" || controller.controller_name == "companies" %>
        <li id="c_view_item"><%= link_to "view all companies",companies_path, :class => "btn btn-primary custom_btn_action"%></li>
        <% if @ud.admin == true %>
          <li id="c_add_item"><%= link_to "add new company", new_company_path, :class => "btn btn-primary custom_btn_action"%></li>
        <% end %>
      <% end %>
      <% if controller.action_name == "policy_handle"|| controller.controller_name == "policies" %>
        <li id="p_view_item"><%= link_to "view all policies",policies_path, :class => "btn btn-primary custom_btn_action"%></li>
        <li id="p_add_item"><%= link_to "add new policy", policies_select_company_path, :class => "btn btn-primary custom_btn_action"%></li>
      <%end%>
      <% if controller.action_name == "user_handle" || controller.controller_name == "details" %>
        <li id="u_view_item"><%= link_to "view all users",details_path, :class => "btn btn-primary custom_btn_action"%></li>
      <% end %>
      <% if controller.action_name == "poltype_handle" || controller.controller_name == "poltypes" %>
        <li id="pl_view_item"><%= link_to "view all plans",poltypes_path, :class => "btn btn-primary custom_btn_action"%></li>
        <% if @ud.admin == true %>
          <li id="pl_add_item"><%= link_to "add new plan", new_poltype_path, :class => "btn btn-primary custom_btn_action"%></li>
        <% end %>
      <% end %>
    </ul>
  </div>

  <p id="a_name"><%= controller.action_name %></p>
  <p id="c_name"><%= controller.controller_name %></p>
  <p id="admin"><%= @ud.admin %></p>
    <script type="text/javascript">

    actionName = $('#a_name').text();
    controllerName = $('#c_name').text();
    admin = $('#admin').text();

    if(admin=="false")
    {


      $( "#p_view_item").find('a').html("my policies");
      $('#c_view_item').hide();
       $('#pl_view_item').hide();
       $('#u_view_item').hide();

    
    }
    
    if (controllerName == "companies")
    {

      if (actionName=="index")
      {
      $('#c_view_item').addClass("active");
      }
      if(actionName=="new"){
       
        $('#c_add_item').addClass("active");
      }
    }
    if (controllerName=="policies")
    {
      if (actionName=="index")
      {
      $('#p_view_item').addClass("active");
      }
      if(actionName=="new"|| actionName=="select_company" || actionName=="select_plan"){
        $('#p_add_item').addClass("active");
      }
    }
      if (controllerName=="details")
    {
      if (actionName=="index")
      {
      $('#u_view_item').addClass("active");
      }
      if(actionName=="new")
      {
        $('#u_view_item').hide();
      }
    }
      if (controllerName=="poltypes")
    {
      if (actionName=="index")
      {
      $('#pl_view_item').addClass("active");
      }
      if(actionName=="new"){
        $('#pl_add_item').addClass("active");
      }
    }
  </script>

<% end %>

app/views/layouts/_navigation.html.erb
<% @c = controller.controller_name %>
<% @a = controller.action_name %>
<% @ac = @c + @a %>
<% if user_signed_in? && @ac != "detailsnew" && @ac != "detailscreate"%>
  <% @user=current_user%>
  <% @detail = @user.detail %>
  <nav class="navbar navbar-default custom_nav">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav " id="extra_padding">
          <li id="policy_h"><%= link_to "Policies", dash_policy_handle_path%></li>
          <% if(@detail.admin==true) %>
            <li id="company_h" ><%= link_to "Companies", dash_company_handle_path%></li>
          <% else %>
            <li id="company_h" ><%= link_to "Companies", companies_path%></li>
          <% end %>
          <% if(@detail.admin==true) %>
            <li id="plan_h" ><%= link_to "Plans", dash_poltype_handle_path%></li>
          <% else %>
            <li id="plan_h" ><%= link_to "Plans", poltypes_path%></li>
          <% end %>
          <% if(@detail.admin==true) %>
            <li id="user_h" > <%= link_to "Users", dash_user_handle_path%></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right" style="text-align: center;">
          <li class="dropdown">
          <a class="dropdown-toggle style-name" data-toggle="dropdown" href="#" style="color:black;"> <%= @detail.first_name %> <%= @detail.last_name %>
          <span class="caret"></span></a>
          <ul class="dropdown-menu" style="text-align: center;">
          <li> <%= link_to "edit", details_cedit_path(:user_id => @detail.user_id)%></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>


          </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <p id="cname"><%= controller.action_name %></p>
  <p id="con_name"><%= controller.controller_name %></p>
<% end %>

<%= stylesheet_link_tag 'dash' %>
<%= javascript_tag 'dash' %>


<script type="text/javascript">

  actionName = $('#cname').text();
  controllerName = $('#con_name').text();
  

  if (actionName == "company_handle" ||  controllerName=="companies")
  {
    $('#company_h').addClass("active");
  }
   if (actionName == "policy_handle" || controllerName=="policies")
  {
    $('#policy_h').addClass("active");
  }
   if (actionName == "poltype_handle" || controllerName=="poltypes")
  {
    $('#plan_h').addClass("active");
  }
   if (actionName == "user_handle" || controllerName== "details")
  {
    if(actionName!= "new")
    $('#user_h').addClass("active");
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Insurance Manager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Handlee|Pacifico|Inconsolata|Comfortaa|Titillium+Web|Bilbo|Patrick+Hand+SC|Dosis|Roboto|Indie Flower|Cookie" rel="stylesheet"> 
  </head>

  <body>
    <% flash.each do |key, value| %><div class="notice-display flash <%= key %>""><%= value %></div><% end %>
    <div class="container-fluid brand">
      <%= link_to dash_customer_path do %>
      <h1>Insurance Manager</h1>
      <%end%>
    </div>
    <%= render 'layouts/navigation' %>

    <% if (controller.controller_name == "companies" || controller.controller_name == "policies" || controller.controller_name == "details" || controller.controller_name == "poltypes" || controller.action_name == "company_handle" || controller.action_name == "policy_handle" || controller.action_name == "user_handle" || controller.action_name == "poltype_handle") %>
      <%= render 'layouts/action_nav' %>
    <% end %>



    <%= yield %>
  </body>
</html>