config/routes.rb
Rails.application.routes.draw do
  get 'dash/admin'
  get 'dash/customer'
  get 'dash/policy_handle'
  get 'dash/user_handle'
  get 'dash/poltype_handle'
  get 'dash/company_handle'
  get 'policies/select_company'
  get 'policies/select_plan'
  get 'details/make_admin'
  get 'details/cedit'
  get 'details/cdestroy'
  get 'details/cshow'
  get 'details/cupdate'
  get 'details/display'
  get 'policies/display'
  get 'companies/companyShow'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :details
  resources :poltypes
  resources :companies
  resources :policies
  resources :posts
  resources :comments
  root to: "sessions#new"

end

app/models/policy.rb
class Policy < ApplicationRecord
	belongs_to :company
	belongs_to :user 
	belongs_to :poltype
  has_many :comment, :dependent => :destroy
	validates :policy_type, presence: true
	validates :sum_insured, presence: true, :numericality => {:only_integer => true}
	validates :premium_amount, presence: true, :numericality => {:only_integer => true}
	validates :commission, presence: true
	validates :purchase_date, presence: true
	validates :mature_date,presence: true
	validates :user_id, presence: true
	validates :company_id, presence: true
	validates :poltype_id, presence: true
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  def index
	  if user_signed_in?
      @policies = Policy.all
      @user = current_user
      @u_detail = @user.detail
    else
      redirect_to new_user_session_path
    end
  end

  def show
  
  end

  def display
    if user_signed_in?
       @policy = Policy.find_by_id(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def select_company
    if user_signed_in?
	    @allcompany = Company.all
	  else
	    redirect_to new_user_session_path
	  end
  end
  def select_plan
    if user_signed_in?
      @c_id = params[:company_id]
    else
      redirect_to new_user_session_path
    end  
	end

  def edit
    if user_signed_in?
      @policy = Policy.find(params[:id])
      @user = current_user
      @u_detail = @user.detail
    else
      edirect_to new_user_session_path

    end
  end

def update
  @policy = Policy.find(params[:id])
  if @policy.update(policy_params)
    redirect_to dash_admin_path, :notice => "policy edited!!" 
  else
    render 'edit'
  end
end

def destroy
  @policy = Policy.find(params[:id])
  @policy.destroy
  redirect_to policies_path, :notice => "policy deleted"
end

  def show
		
  end
  def new
    if user_signed_in?
      @policy= Policy.new
	    @c_id = params[:company_id]
	    @p_id = params[:poltype_id]
      @user = current_user
      @u_detail = @user.detail
      @alluserdetail= Detail.all
	    if @c_id == nil
	  	  redirect_to policies_select_company_path
	    end
    else
       redirect_to new_user_session_path
    end  
  end

  def create
    @policy= Policy.new(policy_params)
	    if @policy.save
  	    redirect_to policies_path, :notice => "policy saved!!" 
  	  else
  		  redirect_to new_policy_path, :notice => "policy could not be saved please enter all details"
  	  end
    end
  private
  def policy_params
    params.require(:policy).permit(:policy_type,:description,:sum_insured,:premium_amount,:commission, :purchase_date, :mature_date, :user_id,:company_id,:poltype_id)
  end
end

app/views/policies/display.html.erb
<div class="container">
  <%= link_to "back", policies_path,:class => "btn btn-primary custom_btn_small" %>
</div>
<% @usrd = Detail.find_by_user_id(current_user.id) %>
<% @usr=User.find(@policy.user_id) %>
<% @ud= @usr.detail %>
<% @com = Company.find(@policy.company_id) %>
<% @plan = Poltype.find(@policy.poltype_id) %>
<div class="container show-box">
  <p><strong>Holder's Name :</strong><%= @ud.first_name%> <%=@ud.last_name%></p><br>
  <p><strong>Company Name :</strong><%= @com.name%></p><br>
  <p><strong>policy Type :</strong><%= @policy.policy_type%></p><br>
  <p><strong>Description :</strong><%= @policy.description%></p><br>
  <p><strong>Sum insured :</strong><%= @policy.sum_insured%></p><br>
  <p><strong>Premium amount :</strong><%= @policy.premium_amount%></p><br>
  <p><strong>Commission :</strong><%= @policy.commission%></p><br>
  <p><strong>Purchase date :</strong><%= @policy.purchase_date%></p><br>
  <p><strong>Mature date :</strong><%= @policy.mature_date%></p><br>
 
  <% if @usrd.admin == true %>
    <td><%= link_to "edit", edit_policy_path(@policy), :class => "btn btn-primary custom_btn_small" %></td>
    <td><%= link_to 'Destroy', policy_path(@policy),
    method: :delete,
    data: { confirm: 'Are you sure?' } , :class => "btn btn-primary custom_btn_small"%></td>
  <% end %>
</div>

app/views/policies/edit.html.erb
<% @det = Detail.find_by_user_id(@policy.user_id) %>
<div class="container" style="max-width: 50%; align-self: center;">
  <h2> edit policy </h2>
  <h3> holder: <%= @det.first_name %> <%= @det.last_name %> </h3>
  <%= simple_form_for @policy do |f| %>
    <% if @policy.errors.any? %>
      <div id="error_explanation" style="color: red;">
        <h2>
        <%= pluralize(@policy.errors.count, "error") %> prohibited
        this policy from being saved:
        </h2>
        <ul>
        <% @policy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.input :user_id, input_html: {value: @policy.user_id}, :readonly => true, :as => :hidden %>
    <%= f.input :description, placeholder: 'description' %>
    <%= f.input :sum_insured, input_html: {value: @policy.sum_insured}, :readonly => true %>
    <%= f.input :premium_amount, input_html: {value: @policy.premium_amount}, :readonly => true %>>
    <%= f.input :commission, input_html: {value: @policy.commission} %>
    <%= f.input :purchase_date, label: "purchase date",  input_html: {value: @policy.purchase_date}, :readonly => true  %>
    <%= f.input :mature_date, label: "mature date",input_html: {value: @policy.mature_date} %>
    <%= f.input :premium_amount, input_html: {value: @policy.premium_amount}, :readonly => true %>
    <%= f.input :company_id, input_html: {value: @policy.company_id}, :readonly => true, :as => :hidden %>
    <%= f.input :poltype_id, input_html: {value: @policy.poltype_id}, :readonly => true, :as => :hidden  %>
    <%= f.input :policy_type, input_html: {value: @policy.policy_type}, :readonly => true %>

    <%= f.submit "create policy", :class => "btn btn-primary custom_btn_small" %>
  <% end %>
</div>

app/views/policies/index.html.erb
<% @policies= Policy.all %>
<% if @u_detail.admin == true %>
<% @pol = @policies %>
<% else %>
<% @pol=Policy.where(:user_id => @user.id) %>
<% end %>
<% if(@pol.count!=0) %>

  <div class="container" >
    <h2 class="form-info">Policies</h2>
    <p class="text-style">this list displays all the available policies bought by user. this list is only for viewing, to buy a policy from a specific company , please visit <strong>Policy --> Add new policy</strong> </p><br><br>                 
    <table class="table table-responsive table-hover">
      <thead>
        <tr>
          <th>holders name</th>
          <th>company name</th>
          <th>policy type</th>
          <th>sum insured</th>
          <th>premium amount</th>
          <th>commission</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @pol.each do |i| %>
          <% @usr=User.find(i.user_id) %>
          <% @detail= @usr.detail %>
          <% @company=Company.find(i.company_id) %>
          <% @poltype=Poltype.find(i.poltype_id) %>
          <tr>
            <% @pol_id = i.id %>
            <% @u_id = current_user.id %>
            <td><%=@detail.first_name%> <%= @detail.last_name%></td>
            <td><%=@company.name%></td>
            <td><%=i.policy_type%></td>
            <td><%=i.sum_insured%></td>
            <td><%=i.premium_amount%></td>
            <td><%=i.commission%></td>
            <td><%= link_to "display", policies_display_path(:id => i.id),:class => "btn btn-primary custom_btn_small" %></td>
            <td><%= link_to "comments", comments_path(:id => i.id),:class => "btn btn-primary custom_btn_small" %></td>
          </tr>

        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="container" >
      <h2 class="form-info">Policies</h2>
      <p class="text-style">no policies to display,  please visit <strong>Policy --> Add new policy</strong></p><br><br>                 
    </div>
<% end %>

app/views/policies/new.html.erb
<% @c_id %>
<% @p_id %>
<% @company= Company.find(@c_id) %>
<% @plan = Poltype.find(@p_id) %>

<p id="pol_duration" class="hidden"><%= @plan.duration %></p>
<p id="pol_ins_amt" class="hidden"><%= @plan.sum_insured %></p>
<h1 class="form-info">Add new policy</h1>
<div class="container box-form">
  <%= simple_form_for @policy do |f| %>
    <% if @policy.errors.any? %>
      <div id="error_explanation" style="color: red;">
        <h2>
        <%= pluralize(@policy.errors.count, "error") %> prohibited
        this policy from being saved:
        </h2>
        <ul>
        <% @policy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% @date= Date.today() + @plan.duration.year %>
    <% if @u_detail.admin == true %>
      <%= f.input :user_id,:collection => @alluserdetail,:label_method => :first_name,:value_method => :user_id,:label => "holder name"%>

    <% else %>
      <%= f.input :user_id, input_html: {value: @u_detail.user_id}, :readonly => true, :as => :hidden %>
    <% end %>

    <%= f.input :description,  input_html: {value: @plan.description}, :readonly => true, :as => :hidden %>
    <%= f.input :sum_insured, input_html: {id: 'sum_ins', value: @plan.sum_insured, min: '1000', step: '15000', max: @plan.sum_insured} %>
    <%= f.input :premium_amount, input_html: {id: 'prem_amt'}, :readonly => true %>
    <%= f.input :commission, input_html: {id: 'com'}, :readonly => true %>
    <%= f.input :purchase_date, label: "purchase date", :selected => Date.today, :readonly => true %>
    <%= f.input :mature_date, label: "mature date", :selected => @date , :readonly => true %>
    <%= f.input :company_id, input_html: {value: @c_id}, :readonly => true, :as => :hidden %>
    <%= f.input :poltype_id, input_html: {value: @p_id}, :readonly => true, :as => :hidden  %>
    <%= f.input :policy_type, input_html: {value: @plan.name}, :readonly => true %>

    <%= f.submit "create policy", :class => "btn btn-primary custom_btn_small" %>
  <% end %>
</div>

<script type="text/javascript">
$( document ).ready(function() {
   v = $('#pol_ins_amt').text();
   dur = $('#pol_duration').text();
     if(dur!=0)
    var total = parseInt(v/dur);
    var com = parseInt(0.2 * total);
    $("#prem_amt").val(total);
    $("#com").val(com)

});
	$("#sum_ins").change(function(){
    dur = $('#pol_duration').text();

    var price = Number($(this).val());
    if(dur!=0)
    var total = parseInt((price)/dur);
    var com = parseInt(0.2 * total);
    $("#prem_amt").val(total);
    $("#com").val(com)
});



function updatePrice(val)
{
    $("#sum_ins").val(val);
    $("#sum_ins").trigger('change');
}

</script>

app/views/policies/select_company.html.erb
<% if(@allcompany.count!=0) %>
  <div class="container">
    <h1 class="form-info">Step 1:   Select a Company</h1>
    <div class="rows">
      <% @allcompany.each do |i| %>
      <%= link_to policies_select_plan_path(:company_id => i.id) do %>
      <div class="col-md-5 company-type-box" >
        <h2><%=i.name%></h2>
        <br>description: <%=i.description%> <br>

      </div>
      <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="container">
    <h1 class="form-info">no companies to display. please come back later</h1>
    
  </div>
<% end %>


<%= stylesheet_link_tag 'policies' %>

app/views/policies/select_plan.html.erb
<% @c_id %>
<% @plans=Poltype.where(:company_id => @c_id) %>
<% if @plans.count!=0 %>
  <div class="container">
    <h1 class="form-info">Step 2:   Select a policy</h1>
    <div class="rows">
      <% @plans.each do |i| %> 
      <%= link_to new_policy_path(:company_id => @c_id,:poltype_id => i.id) do %>
      <div class="col-md-5 policy-type-box" >
        <h2><%=i.name%></h2>
        <br><strong>description:</strong> <%=i.description%> <br>
        <br><strong>duration:</strong> <%=i.duration%> <br>
        <br><strong>Insured Amount:</strong> <%=i.sum_insured%> INR <br>
        <br><strong>Premium Amount:</strong> <%=i.premium_amount%> INR<br>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
<% else %>
  <% @c= Company.find(@c_id) %>
  <div class="container">
    <h1 class="form-info">no policies for the chosen company : <%= @c.name %> <br>choose a different company</h1>
    
    <%= link_to " go back", policies_select_company_path,:class => "btn btn-primary custom_btn_small" %>
  </div>
<% end %>

<%= stylesheet_link_tag 'policies' %>